# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Intel IOMMU driver in pKVM

ccflags-$(CONFIG_PKVM_INTEL) += -I $(srctree)/drivers/iommu/intel

pkvm-iommu := ../../../../drivers/iommu/intel/pkvm
intel-iommu := ../../../../drivers/iommu/intel

pkvm-hyp-$(CONFIG_PKVM_INTEL) += $(pkvm-iommu)/iommu.o \
				 $(pkvm-iommu)/iommu_pmu.o \
				 $(pkvm-iommu)/iommu_hc.o \
				 $(pkvm-iommu)/domain.o \
				 $(pkvm-iommu)/pgtable.o \
				 $(pkvm-iommu)/device.o \
				 $(pkvm-iommu)/cache.o \
				 $(intel-iommu)/dmar.o \
				 $(intel-iommu)/iommu.o \
				 $(intel-iommu)/pasid.o \
				 $(intel-iommu)/cache.o
